name: Publish
on:
  release:
    types: [created]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org/"

      # Ensure latest version of npm is installed to take advantage of new
      # security features
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build
      - run: npm publish
